// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateChapter(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateChapter'](arg1, arg2, arg3);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function DeleteChapter(arg1) {
  return window['go']['main']['App']['DeleteChapter'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetChapter(arg1) {
  return window['go']['main']['App']['GetChapter'](arg1);
}

export function GetChapters(arg1) {
  return window['go']['main']['App']['GetChapters'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function ReorderChapters(arg1, arg2) {
  return window['go']['main']['App']['ReorderChapters'](arg1, arg2);
}

export function UpdateChapter(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateChapter'](arg1, arg2, arg3);
}

export function UpdateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2, arg3);
}
