// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateChapter(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateChapter'](arg1, arg2, arg3);
}

export function CreateCharacter(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateCharacter'](arg1, arg2, arg3, arg4);
}

export function CreateParagraph(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateParagraph'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function DeleteChapter(arg1) {
  return window['go']['main']['App']['DeleteChapter'](arg1);
}

export function DeleteCharacter(arg1) {
  return window['go']['main']['App']['DeleteCharacter'](arg1);
}

export function DeleteParagraph(arg1) {
  return window['go']['main']['App']['DeleteParagraph'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetChapter(arg1) {
  return window['go']['main']['App']['GetChapter'](arg1);
}

export function GetChapters(arg1) {
  return window['go']['main']['App']['GetChapters'](arg1);
}

export function GetCharacter(arg1) {
  return window['go']['main']['App']['GetCharacter'](arg1);
}

export function GetCharacters(arg1) {
  return window['go']['main']['App']['GetCharacters'](arg1);
}

export function GetLLMConfig() {
  return window['go']['main']['App']['GetLLMConfig']();
}

export function GetParagraph(arg1) {
  return window['go']['main']['App']['GetParagraph'](arg1);
}

export function GetParagraphs(arg1) {
  return window['go']['main']['App']['GetParagraphs'](arg1);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetVoice(arg1) {
  return window['go']['main']['App']['GetVoice'](arg1);
}

export function GetVoices() {
  return window['go']['main']['App']['GetVoices']();
}

export function ReorderChapters(arg1, arg2) {
  return window['go']['main']['App']['ReorderChapters'](arg1, arg2);
}

export function SetLLMConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetLLMConfig'](arg1, arg2, arg3);
}

export function SplitParagraph(arg1) {
  return window['go']['main']['App']['SplitParagraph'](arg1);
}

export function SplitParagraphPreview(arg1) {
  return window['go']['main']['App']['SplitParagraphPreview'](arg1);
}

export function UpdateChapter(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateChapter'](arg1, arg2, arg3);
}

export function UpdateCharacter(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateCharacter'](arg1, arg2, arg3, arg4);
}

export function UpdateParagraph(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['UpdateParagraph'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function UpdateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2, arg3);
}
