// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {repositories} from '../models';

export function CreateChapter(arg1:number,arg2:string,arg3:string):Promise<number>;

export function CreateProject(arg1:string,arg2:string):Promise<number>;

export function DeleteChapter(arg1:number):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function GetChapter(arg1:number):Promise<repositories.Chapter>;

export function GetChapters(arg1:number):Promise<Array<repositories.Chapter>>;

export function GetProject(arg1:number):Promise<repositories.Project>;

export function GetProjects():Promise<Array<repositories.Project>>;

export function ReorderChapters(arg1:number,arg2:Array<number>):Promise<void>;

export function UpdateChapter(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateProject(arg1:number,arg2:string,arg3:string):Promise<void>;
