// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {utils} from '../models';

export function CreateChapter(arg1:number,arg2:string,arg3:string):Promise<number>;

export function CreateCharacter(arg1:number,arg2:string,arg3:string,arg4:string):Promise<number>;

export function CreateParagraph(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<number>;

export function CreateProject(arg1:string,arg2:string):Promise<number>;

export function DeleteChapter(arg1:number):Promise<void>;

export function DeleteCharacter(arg1:number):Promise<void>;

export function DeleteParagraph(arg1:number):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function DeleteProjectKnownCharacter(arg1:number,arg2:string):Promise<void>;

export function GenerateBatchAudio(arg1:Array<number>):Promise<Array<models.Paragraph>>;

export function GenerateChapterAudio(arg1:number):Promise<Array<models.Paragraph>>;

export function GenerateParagraphAudio(arg1:number):Promise<models.Paragraph>;

export function GetChapter(arg1:number):Promise<models.Chapter>;

export function GetChapters(arg1:number):Promise<Array<models.Chapter>>;

export function GetCharacter(arg1:number):Promise<models.Character>;

export function GetCharacters(arg1:number):Promise<Array<models.Character>>;

export function GetLLMConfig():Promise<utils.LLMConfig>;

export function GetParagraph(arg1:number):Promise<models.Paragraph>;

export function GetParagraphs(arg1:number):Promise<Array<models.Paragraph>>;

export function GetProject(arg1:number):Promise<models.Project>;

export function GetProjectKnownCharacters(arg1:number):Promise<Array<models.CharacterInfo>>;

export function GetProjectLLMApiKey(arg1:number):Promise<string>;

export function GetProjectTTSApiKey(arg1:number):Promise<string>;

export function GetProjects():Promise<Array<models.Project>>;

export function GetTTSConfig():Promise<utils.TTSConfig>;

export function GetVoice(arg1:string):Promise<models.Voice>;

export function GetVoices():Promise<Array<models.Voice>>;

export function Log(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReorderChapters(arg1:number,arg2:Array<number>):Promise<void>;

export function SetKnownCharacterVoice(arg1:number,arg2:string,arg3:string):Promise<void>;

export function SetLLMConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetProjectLLMApiKey(arg1:number,arg2:string):Promise<void>;

export function SetProjectTTSApiKey(arg1:number,arg2:string):Promise<void>;

export function SetTTSConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SplitParagraph(arg1:number):Promise<Array<models.Paragraph>>;

export function SplitParagraphPreview(arg1:string):Promise<Array<models.Paragraph>>;

export function UpdateChapter(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateCharacter(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateKnownCharacter(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>):Promise<void>;

export function UpdateNarratorVoice(arg1:number,arg2:string):Promise<void>;

export function UpdateParagraph(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:string,arg8:number,arg9:number):Promise<void>;

export function UpdateProject(arg1:number,arg2:string,arg3:string):Promise<void>;

export function UpdateProjectKnownCharacters(arg1:number,arg2:Array<models.CharacterInfo>):Promise<void>;
